In [1]:
import numpy as np

In [3]:
a= np.array(10)
print(a)


10


In [4]:
#scalar quentity
print("Add",a + 5)

Add 15


In [5]:
print("subtract",a - 5)

subtract 5


In [6]:
print("Multiply",a * 5)

Multiply 50


In [7]:
print("Division",a / 5)

Division 2.0


In [8]:
#Vector (1-D array)

vec=np.array([1,2,3,4,5,6])
print(vec)


[1 2 3 4 5 6]


In [9]:
vec * 3

array([ 3,  6,  9, 12, 15, 18])

In [10]:
print(vec + 15)

[16 17 18 19 20 21]


In [11]:
print(vec + vec)

[ 2  4  6  8 10 12]


In [12]:
print(vec - vec)


[0 0 0 0 0 0]


In [13]:
# Matrix (2-D Array) Rows & Columns
mat=np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [14]:
mat + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
mat * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
print(mat + 3)

[[4 5 6]
 [7 8 9]]


In [18]:
Mat1=np.array([[1,2],[3,4]])

Mat2=np.array([[5,6],[7,8]])

In [20]:
Mat1

array([[1, 2],
       [3, 4]])

In [21]:
Mat2

array([[5, 6],
       [7, 8]])

In [19]:
Mat1 + Mat2

array([[ 6,  8],
       [10, 12]])

In [22]:
Mat1 * Mat2

array([[ 5, 12],
       [21, 32]])

In [24]:
Mat1.shape

(2, 2)

In [26]:
#Transpose a matrix
Mat1.T

array([[1, 3],
       [2, 4]])

In [27]:
#determinant
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [32]:
det=np.linalg.det(A)
print(det)
# det=ad-bc  formula

-2.0000000000000004


In [28]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
det=np.linalg.det(B)
print(det)
# det=a(ei-fh)-b(di-fg)+c(dh-eg)  Formula

0.0


In [33]:
# identity matrix
Iden=np.eye(3)
print(Iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#Diagonal Matrix
diag=np.diag([1,5,9])
print(diag)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [44]:
#Linear Equation
A=np.array([[1,2],
            [3,4]])

B=np.array([5,6])

In [41]:
#Solve linear equation
x=np.linalg.solve(A,B)
print(x)

[-4.   4.5]


In [42]:
A

array([[1, 2],
       [3, 4]])

In [43]:
B

array([5, 6])

In [47]:
#Linear Equation
A=np.array([[4,5,3],
            [4,1,6],
           [9,8,9]
           ])

B=np.array([6,8,9])

In [48]:
x=np.linalg.solve(A,B)
print(x)

[-53.          24.          32.66666667]


In [49]:
A

array([[4, 5, 3],
       [4, 1, 6],
       [9, 8, 9]])

In [51]:
B

array([6, 8, 9])

In [3]:
#SVD- Singular Value Decomposition

import numpy as np

In [4]:
marks= np.array([[80,90,np.nan],
                 [60,np.nan,70],
                 [90,85,88],
                 [np.nan,55,60],
                 [75,np.nan,np.nan]])


In [5]:
marks

array([[80., 90., nan],
       [60., nan, 70.],
       [90., 85., 88.],
       [nan, 55., 60.],
       [75., nan, nan]])

In [6]:
upd_marks=np.nanmean(marks,axis=1)

In [7]:
upd_marks

array([85.        , 65.        , 87.66666667, 57.5       , 75.        ])

In [8]:
#Replace NaN with student-wise mean
filled_marks=np.where(np.isnan(marks),upd_marks[:,np.newaxis],marks)

In [9]:
filled_marks

array([[80. , 90. , 85. ],
       [60. , 65. , 70. ],
       [90. , 85. , 88. ],
       [57.5, 55. , 60. ],
       [75. , 75. , 75. ]])

In [13]:
#Perform SVD
U,S,VT=np.linalg.svd(filled_marks,full_matrices=False)

In [14]:
#Reconstruct approximate marks matrix
k=2 #it will keep the top 2 most imp marks pattern

U_k = U[:, :k] #Most imp student pattern
S_k = np.diag(S[:k]) #how much is the strength of the pattern
VT_k = VT[:k, :] #Most imp subject in the dataset

approx_marks = U_k @ S_k @ VT_k #contruct the matrix with most imp features

In [15]:
approx_marks

array([[79.17814905, 88.63339268, 87.13686458],
       [61.32249846, 67.19910444, 66.56142014],
       [89.75906875, 84.59936968, 88.62643652],
       [58.16957831, 56.11340215, 58.25905394],
       [74.55267067, 74.25616252, 76.16308462]])

In [ ]:
#Movie Rating matrix
